
- name: Provision Web Servers
  hosts: tag_group_web
  become: true
  tasks:
    - name: Install python pip
      apt:
        update_cache: yes
        name:
          - python3-pip
          - docker.io
              
    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: copy nginx folder to /opt
      copy:
        src: ../../nginx
        dest: /opt

    - name: copy staycation folder to /opt
      copy:
        src: ../../staycationX
        dest: /opt
   
    - name: Run docker-compose
      shell: docker-compose -f /opt/staycationX/docker-compose.yml up -d --build
   